config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations' }
  devise_scope :user do
    post '/downgrade' => 'users/registrations#downgrade', as: :downgrade
  end

  resources :wikis do
    resources :collaborators, only: :create
  end

  resources :charges, only: [:new, :create]

  root 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="text-center">
  <h1 class="top-header">Blocipedia: Social, Markdown Wikis</h1>

  <div class="jumbotron">
    <h3 class="jumbo-header">Create and share Markdown Wikis</h3>
    <p>
      <% if user_signed_in? %>
        <%= link_to "Wikis", wikis_path, class: 'btn btn-primary btn-lg' %>
      <% else %>
        <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary btn-lg' %>
      <% end %>
    </p>
  </div>

  <div class="row">
    <div class="col-md-6">
      <h5 class="plan-tagline">Create as many public wikis as you want!</h5>
      <p>
        <% if user_signed_in? %>
          <%= link_to "Profile", edit_user_registration_path, class: 'btn btn-primary btn-lg' %>
        <% else %>
          <%= link_to "Free", new_user_registration_path, class: 'btn btn-primary btn-lg' %>
        <% end %>
      </p>
    </div>
    <div class="col-md-6">
      <h5 class="plan-tagline">Create private wikis!</h5>
      <p>
        <% if current_user && current_user.standard? %>
          <%= link_to "Premium", new_charge_path , class: 'btn btn-primary btn-lg' %>
        <% else %>
          <%= link_to "New Wiki", new_wiki_path , class: 'btn btn-primary btn-lg'%>
        <% end %>
      </p>
    </div>
  </div>
</div>