config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations' }
  devise_scope :user do
    post '/downgrade' => 'users/registrations#downgrade', as: :downgrade
  end

  resources :wikis do
    resources :collaborators, only: :create
  end

  resources :charges, only: [:new, :create]

  root 'welcome#index'
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user

  has_many :collaborators
  has_many :users, through: :collaborators

  validates :title, length: { minimum: 3 }, presence: true
  validates :body, length: { minimum: 15 }, presence: true
  validates :user, presence: true

  def public?
    !self.private?
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_user,  except: [:index, :show], if: :private_wiki?

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find_by_id( params[:id] )
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @wiki = Wiki.new( wiki_params )
    @wiki.user = current_user

    authorize @wiki
    if @wiki.save
      flash[:notice] = "Wiki was successfully created"
      redirect_to @wiki
    else
      flash.now[:alert] = "Wiki creation unsuccessful. Try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find_by_id( params[:id] )
    authorize @wiki
    @users = User.all 
  end

  def update
    @wiki = Wiki.find_by_id( params[:id] )

    authorize @wiki
    if @wiki.update( wiki_params )
      flash[:notice] = "Wiki updated!"
      redirect_to @wiki
    else
      flash.now[:alert] = "Error saving wiki. Try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find_by_id( params[:id] )

    authorize @wiki
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted."
      redirect_to action: :index
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end

  def private_wiki?
    @wiki && @wiki.private?
  end

  def authorize_user
    unless current_user.admin? || current_user.premium?
      flash[:alert] = "You must have a Premium membership to create private wikis."
      redirect_to new_charge_path
    end
  end
end

app/helpers/wikis_helper.rb
module WikisHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { target: "_blank" }
    }

    extensions = {
      autolink:           true,
      tables:             true,
      superscript:        true,
      fenced_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/views/wikis/_form.html.erb
<%= form_for [wiki] do |f| %>
  <%  if wiki.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(wiki.errors.count, "error") %>.</h4>
      <ul>
        <% wiki.errors.full_messages.each do |msg| %>
        <li><%=  msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_group_tag(wiki.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  <% end %>
  <%= form_group_tag(wiki.errors[:body]) do %>
    <%= f.label :body %>
    <%= f.text_area :body, rows: 16, class: 'form-control', placeholder: "Enter wiki body" %>
  <% end %>
  <% if current_user.admin? || current_user.premium? %>
    <div class="form-group">
      <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private wiki
      <% end %>
    </div>
  <% end %>
  <%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/wikis/_wiki.html.erb
<tr>
  <td><%= link_to wiki.title, wiki %></td>
  <% if current_user && (current_user.admin? || current_user.premium?) %>
    <td class="text-center">
      <% if wiki.private? %>
        <%= "private" %>
      <% else %>
        <%= "public" %>
      <% end %>
    </td>
  <% end %>
  <% if user_signed_in? %>
    <td class="text-center"><%= link_to "edit", edit_wiki_path(wiki) %></td>
    <td class="text-center"><%= link_to "delete", wiki, method: :delete, data: { confirm: 'Delete this wiki?' } %></td>
    <td class="text-center"><i class="glyphicon glyphicon-star-empty"> </i></td>
  <% end %>
</tr>

app/views/wikis/edit.html.erb
<div class="row">
  <div class="col-md-offset-1">
    <div class="col-md-5">
      <h2>Edit Wiki</h2>

      <%= render partial: 'form', locals: { wiki: @wiki } %>

      <% if @wiki.private? %>
        <h4>Add Collaborators to the <%= @wiki.title %> wiki</h4>
        <%= form_tag wiki_collaborators_path(@wiki) do %>
          <table class="table table-striped table-bordered">
            <th>Username</th>
            <th>Email</th>
            <th>Give Access</th>
            <% @users.each do |user| %>
              <%= render partial: 'collaborators/collaborator', locals: { wiki: @wiki, user: user } %>
            <% end %>
          </table>
          <%= submit_tag "Share Wiki", class: 'btn btn-primary'%>
        <% end %>
      <% end %>
    </div>
    <div class="col-md-5">

    </div>
  </div>
</div>

app/views/wikis/index.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h2 class="text-center">My Wikis</h2>
    <table class="table table-striped table-bordered">
      <%= render @wikis %>
    </table>

    <div class="text-center">
      <% if current_user %>
        <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>
</div>

app/views/wikis/new.html.erb
<div class="row">
  <div class="col-md-offset-1">
    <div class="col-md-5">
      <h2 class="text-center">New Wiki</h2>

      <%= render partial: 'form', locals: { wiki: @wiki } %>
    </div>
    <div class="col-md-5">
      <h2 class="text-center">Preview</h2>
      <div id="epiceditor"></div>
    </div>

  </div>
</div>

app/views/wikis/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1><%= @wiki.title %></h1>
    <small>
      submitted <%= time_ago_in_words(@wiki.created_at) %> ago by <%= @wiki.user.username %>
    </small>
    <div class="media">
      <p><%= markdown(@wiki.body) %></p>
    </div>

    <% if user_signed_in? %>
      <%= link_to "Edit Wiki", edit_wiki_path, class: 'btn btn-info' %>
      <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Delete this wiki?' } %>
    <% end %>

    <% if @wiki.private? && @wiki.users.count > 0 %>
      <h4>Collaborators</h4>
      <table class="table table-striped table-bordered">
        <th>Username</th>
        <th>Email</th>
        <% @wiki.users.each do |user| %>
        <tr>
          <td><%= user.username %></td>
          <td><%= user.email %></td>
        </tr>
        <% end %>
      </table>
    <% end %>
  </div>
</div>